export const WARNING_NOTIFICATION = 'WARNING_NOTIFICATION';
export const CLEAR_WARNING = 'CLEAR_WARNING';

export const SIGNUP_USER_START = 'SIGNUP_USER_START';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_ERROR = 'SIGNUP_USER_ERROR';
